// Ordering Domain Enums

export enum MasterOrderStatus {
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  PAYMENT_CONFIRMED = 'PAYMENT_CONFIRMED',
  PARTIALLY_FULFILLED = 'PARTIALLY_FULFILLED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
}

export enum SubOrderStatus {
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  PAYMENT_CONFIRMED = 'PAYMENT_CONFIRMED',
  CONFIRMED = 'CONFIRMED',
  PREPARING = 'PREPARING',
  READY = 'READY',
  COLLECTED = 'COLLECTED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
  REFUND_PENDING = 'REFUND_PENDING',
  REFUNDED = 'REFUNDED',
  EXPIRED = 'EXPIRED',
  MISSED_PICKUP = 'MISSED_PICKUP',
}
