// Identity Domain Enums

export enum UserRole {
  STUDENT = 'STUDENT',
  STALL_OWNER = 'STALL_OWNER',
  ADMIN = 'ADMIN',
  STALL_STAFF = 'STALL_STAFF',
}

export enum StudentAccountStatus {
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  REJECTED = 'REJECTED',
}

export enum VerificationStatus {
  PENDING_SUBMISSION = 'PENDING_SUBMISSION',
  UNDER_REVIEW = 'UNDER_REVIEW',
  ACTIVE = 'ACTIVE',
  REJECTED = 'REJECTED',
  SUSPENDED = 'SUSPENDED',
}

export enum VerificationRejectionReason {
  INVALID_DOCUMENT = 'INVALID_DOCUMENT',
  DOCUMENT_UNREADABLE = 'DOCUMENT_UNREADABLE',
  WRONG_DOCUMENT_TYPE = 'WRONG_DOCUMENT_TYPE',
  IDENTITY_MISMATCH = 'IDENTITY_MISMATCH',
  EXPIRED_DOCUMENT = 'EXPIRED_DOCUMENT',
  INSUFFICIENT_INFORMATION = 'INSUFFICIENT_INFORMATION',
  DUPLICATE_SUBMISSION = 'DUPLICATE_SUBMISSION',
  OTHER = 'OTHER',
}

export enum LivenessChallengeType {
  NATURAL_BLINK = 'NATURAL_BLINK',
  HEAD_TURN_LEFT = 'HEAD_TURN_LEFT',
  HEAD_TURN_RIGHT = 'HEAD_TURN_RIGHT',
}

export enum LivenessSessionStatus {
  PENDING = 'PENDING',
  PASSED = 'PASSED',
  FAILED = 'FAILED',
  EXPIRED = 'EXPIRED',
}

export enum LivenessDecision {
  LIVE = 'LIVE',
  SPOOF = 'SPOOF',
  INCONCLUSIVE = 'INCONCLUSIVE',
}

