export enum DomainEventType {
  // Phase 5 Authoritative Payment Bridges
  ORDER_PAYMENT_CONFIRMED = 'ORDER_PAYMENT_CONFIRMED',
  BALANCE_PAYMENT_CONFIRMED = 'BALANCE_PAYMENT_CONFIRMED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_EXPIRED = 'PAYMENT_EXPIRED',
  REFUND_PROCESSED = 'REFUND_PROCESSED',

  // Phase 3 Authoritative SubOrder Bridges
  SUBORDER_CONFIRMED = 'SUBORDER_CONFIRMED',
  SUBORDER_PREPARING = 'SUBORDER_PREPARING',
  SUBORDER_READY = 'SUBORDER_READY',
  SUBORDER_COLLECTED = 'SUBORDER_COLLECTED',
  SUBORDER_REJECTED = 'SUBORDER_REJECTED',

  // Kitchen Operational Alerts
  KITCHEN_ORDER_INCOMING = 'KITCHEN_ORDER_INCOMING',
  KITCHEN_SURGE_ALERT = 'KITCHEN_SURGE_ALERT',
  PICKUP_GRACE_WARNING = 'PICKUP_GRACE_WARNING',
  PICKUP_GRACE_EXPIRED = 'PICKUP_GRACE_EXPIRED',

  // Stream Control Events
  RESYNC_REQUIRED = 'RESYNC_REQUIRED',
  SESSION_TERMINATED = 'SESSION_TERMINATED',
}

export enum KitchenQueueState {
  QUEUED = 'QUEUED',
  IN_PREPARATION = 'IN_PREPARATION',
  READY_FOR_PICKUP = 'READY_FOR_PICKUP',
  COMPLETED = 'COMPLETED',
  REJECTED = 'REJECTED',
  EXPIRED_UNCOLLECTED = 'EXPIRED_UNCOLLECTED',
}
