-- CreateEnum
CREATE TYPE "VerificationRejectionReason" AS ENUM ('INVALID_DOCUMENT', 'DOCUMENT_UNREADABLE', 'WRONG_DOCUMENT_TYPE', 'IDENTITY_MISMATCH', 'EXPIRED_DOCUMENT', 'INSUFFICIENT_INFORMATION', 'DUPLICATE_SUBMISSION', 'OTHER');

-- AlterEnum
ALTER TYPE "AuditActionType" ADD VALUE 'STUDENT_DOCUMENT_SUBMITTED';
ALTER TYPE "AuditActionType" ADD VALUE 'VERIFICATION_REVIEW_STARTED';
ALTER TYPE "AuditActionType" ADD VALUE 'VERIFICATION_APPROVED';
ALTER TYPE "AuditActionType" ADD VALUE 'VERIFICATION_REJECTED';
ALTER TYPE "AuditActionType" ADD VALUE 'STUDENT_SUSPENDED';
ALTER TYPE "AuditActionType" ADD VALUE 'STUDENT_REACTIVATED';
ALTER TYPE "AuditActionType" ADD VALUE 'STUDENT_DOCUMENT_ACCESSED';

-- AlterEnum
ALTER TYPE "VerificationStatus" ADD VALUE 'PENDING_SUBMISSION';
ALTER TYPE "VerificationStatus" ADD VALUE 'UNDER_REVIEW';
ALTER TYPE "VerificationStatus" ADD VALUE 'ACTIVE';
ALTER TYPE "VerificationStatus" ADD VALUE 'SUSPENDED';
